/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;
import Form.Form_Main;
import static Form.Form_Main.number_Choose;
/**
 *
 * @author Ruster
 */
public class Choice extends javax.swing.JFrame {

    /**
     * Creates new form Choice
     */
    public Choice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
 regenerated by the Form_Main Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 250, 0, 0));
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String num1 = "1";
        if(number_Choose == 1){Form_Main.btnSquare1.setText(num1);}if(number_Choose == 4){Form_Main.btnSquare4.setText(num1);}
        if(number_Choose == 5){Form_Main.btnSquare5.setText(num1);}if(number_Choose == 6){Form_Main.btnSquare6.setText(num1);}
        if(number_Choose == 13){Form_Main.btnSquare13.setText(num1);}if(number_Choose == 14){Form_Main.btnSquare14.setText(num1);}
        if(number_Choose == 15){Form_Main.btnSquare15.setText(num1);}if(number_Choose == 22){Form_Main.btnSquare22.setText(num1);}
        if(number_Choose == 23){Form_Main.btnSquare23.setText(num1);}if(number_Choose == 24){Form_Main.btnSquare24.setText(num1);}
        if(number_Choose == 7){Form_Main.btnSquare7.setText(num1);}
        
        if(number_Choose == 2){Form_Main.btnSquare2.setText(num1);}if(number_Choose == 8){Form_Main.btnSquare8.setText(num1);}
        if(number_Choose == 9){Form_Main.btnSquare9.setText(num1);}if(number_Choose == 16){Form_Main.btnSquare16.setText(num1);}
        if(number_Choose == 17){Form_Main.btnSquare17.setText(num1);}if(number_Choose == 18){Form_Main.btnSquare18.setText(num1);}
        if(number_Choose == 25){Form_Main.btnSquare25.setText(num1);}if(number_Choose == 26){Form_Main.btnSquare26.setText(num1);}
        if(number_Choose == 27){Form_Main.btnSquare27.setText(num1);}if(number_Choose == 28){Form_Main.btnSquare28.setText(num1);}
        if(number_Choose == 29){Form_Main.btnSquare29.setText(num1);}
        
        if(number_Choose == 3){Form_Main.btnSquare3.setText(num1);}if(number_Choose == 30){Form_Main.btnSquare30.setText(num1);}
        if(number_Choose == 31){Form_Main.btnSquare31.setText(num1);}if(number_Choose == 32){Form_Main.btnSquare32.setText(num1);}
        if(number_Choose == 33){Form_Main.btnSquare33.setText(num1);}if(number_Choose == 34){Form_Main.btnSquare34.setText(num1);}
        if(number_Choose == 35){Form_Main.btnSquare35.setText(num1);}if(number_Choose == 36){Form_Main.btnSquare36.setText(num1);}
        if(number_Choose == 37){Form_Main.btnSquare37.setText(num1);}if(number_Choose == 38){Form_Main.btnSquare38.setText(num1);}
        if(number_Choose == 39){Form_Main.btnSquare39.setText(num1);}
        
        if(number_Choose == 40){Form_Main.btnSquare40.setText(num1);}if(number_Choose == 41){Form_Main.btnSquare41.setText(num1);}
        if(number_Choose == 42){Form_Main.btnSquare42.setText(num1);}if(number_Choose == 10){Form_Main.btnSquare10.setText(num1);}
        if(number_Choose == 43){Form_Main.btnSquare43.setText(num1);}if(number_Choose == 44){Form_Main.btnSquare44.setText(num1);}
        if(number_Choose == 45){Form_Main.btnSquare45.setText(num1);}if(number_Choose == 46){Form_Main.btnSquare46.setText(num1);}
        if(number_Choose == 47){Form_Main.btnSquare47.setText(num1);}if(number_Choose == 48){Form_Main.btnSquare48.setText(num1);}
        if(number_Choose == 49){Form_Main.btnSquare49.setText(num1);}if(number_Choose == 50){Form_Main.btnSquare50.setText(num1);}
        if(number_Choose == 51){Form_Main.btnSquare51.setText(num1);}if(number_Choose == 52){Form_Main.btnSquare52.setText(num1);}
        if(number_Choose == 53){Form_Main.btnSquare53.setText(num1);}if(number_Choose == 54){Form_Main.btnSquare54.setText(num1);}
        
        if(number_Choose == 11){Form_Main.btnSquare11.setText(num1);}if(number_Choose == 55){Form_Main.btnSquare55.setText(num1);}
        if(number_Choose == 56){Form_Main.btnSquare56.setText(num1);}if(number_Choose == 57){Form_Main.btnSquare57.setText(num1);}
        if(number_Choose == 58){Form_Main.btnSquare58.setText(num1);}if(number_Choose == 59){Form_Main.btnSquare59.setText(num1);}
        
        if(number_Choose == 6){Form_Main.jButton6.setText(num1);}if(number_Choose == 60){Form_Main.btnSquare60.setText(num1);}
        if(number_Choose == 61){Form_Main.btnSquare61.setText(num1);}if(number_Choose == 62){Form_Main.btnSquare62.setText(num1);}
        if(number_Choose == 63){Form_Main.btnSquare63.setText(num1);}if(number_Choose == 64){Form_Main.btnSquare64.setText(num1);}
        if(number_Choose == 65){Form_Main.btnSquare65.setText(num1);}if(number_Choose == 66){Form_Main.btnSquare66.setText(num1);}
        if(number_Choose == 67){Form_Main.btnSquare67.setText(num1);}if(number_Choose == 68){Form_Main.btnSquare68.setText(num1);}
        if(number_Choose == 69){Form_Main.btnSquare69.setText(num1);}
        
        if(number_Choose == 19){Form_Main.btnSquare19.setText(num1);}if(number_Choose == 70){Form_Main.btnSquare70.setText(num1);}
        if(number_Choose == 71){Form_Main.btnSquare71.setText(num1);}if(number_Choose == 72){Form_Main.btnSquare72.setText(num1);}
        if(number_Choose == 73){Form_Main.btnSquare73.setText(num1);}if(number_Choose == 74){Form_Main.btnSquare74.setText(num1);}
        if(number_Choose == 75){Form_Main.btnSquare75.setText(num1);}if(number_Choose == 76){Form_Main.btnSquare76.setText(num1);}
        if(number_Choose == 77){Form_Main.btnSquare77.setText(num1);}if(number_Choose == 78){Form_Main.btnSquare78.setText(num1);}
        if(number_Choose == 79){Form_Main.btnSquare79.setText(num1);}
        
        if(number_Choose == 20){Form_Main.btnSquare20.setText(num1);}if(number_Choose == 80){Form_Main.btnSquare80.setText(num1);}
        if(number_Choose == 81){Form_Main.btnSquare81.setText(num1);}
        
        if(number_Choose == 21){Form_Main.btnSquare21.setText(num1);}
        if(number_Choose == 12){Form_Main.btnSquare12.setText(num1);}
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String num2 = "2";
        if(number_Choose == 1){Form_Main.btnSquare1.setText(num2);}if(number_Choose == 4){Form_Main.btnSquare4.setText(num2);}
        if(number_Choose == 5){Form_Main.btnSquare5.setText(num2);}if(number_Choose == 6){Form_Main.btnSquare6.setText(num2);}
        if(number_Choose == 13){Form_Main.btnSquare13.setText(num2);}if(number_Choose == 14){Form_Main.btnSquare14.setText(num2);}
        if(number_Choose == 15){Form_Main.btnSquare15.setText(num2);}if(number_Choose == 22){Form_Main.btnSquare22.setText(num2);}
        if(number_Choose == 23){Form_Main.btnSquare23.setText(num2);}if(number_Choose == 24){Form_Main.btnSquare24.setText(num2);}
        if(number_Choose == 7){Form_Main.btnSquare7.setText(num2);}
        
        if(number_Choose == 2){Form_Main.btnSquare2.setText(num2);}if(number_Choose == 8){Form_Main.btnSquare8.setText(num2);}
        if(number_Choose == 9){Form_Main.btnSquare9.setText(num2);}if(number_Choose == 16){Form_Main.btnSquare16.setText(num2);}
        if(number_Choose == 17){Form_Main.btnSquare17.setText(num2);}if(number_Choose == 18){Form_Main.btnSquare18.setText(num2);}
        if(number_Choose == 25){Form_Main.btnSquare25.setText(num2);}if(number_Choose == 26){Form_Main.btnSquare26.setText(num2);}
        if(number_Choose == 27){Form_Main.btnSquare27.setText(num2);}if(number_Choose == 28){Form_Main.btnSquare28.setText(num2);}
        if(number_Choose == 29){Form_Main.btnSquare29.setText(num2);}
        
        if(number_Choose == 3){Form_Main.btnSquare3.setText(num2);}if(number_Choose == 30){Form_Main.btnSquare30.setText(num2);}
        if(number_Choose == 31){Form_Main.btnSquare31.setText(num2);}if(number_Choose == 32){Form_Main.btnSquare32.setText(num2);}
        if(number_Choose == 33){Form_Main.btnSquare33.setText(num2);}if(number_Choose == 34){Form_Main.btnSquare34.setText(num2);}
        if(number_Choose == 35){Form_Main.btnSquare35.setText(num2);}if(number_Choose == 36){Form_Main.btnSquare36.setText(num2);}
        if(number_Choose == 37){Form_Main.btnSquare37.setText(num2);}if(number_Choose == 38){Form_Main.btnSquare38.setText(num2);}
        if(number_Choose == 39){Form_Main.btnSquare39.setText(num2);}
        
        if(number_Choose == 40){Form_Main.btnSquare40.setText(num2);}if(number_Choose == 41){Form_Main.btnSquare41.setText(num2);}
        if(number_Choose == 42){Form_Main.btnSquare42.setText(num2);}if(number_Choose == 10){Form_Main.btnSquare10.setText(num2);}
        if(number_Choose == 43){Form_Main.btnSquare43.setText(num2);}if(number_Choose == 44){Form_Main.btnSquare44.setText(num2);}
        if(number_Choose == 45){Form_Main.btnSquare45.setText(num2);}if(number_Choose == 46){Form_Main.btnSquare46.setText(num2);}
        if(number_Choose == 47){Form_Main.btnSquare47.setText(num2);}if(number_Choose == 48){Form_Main.btnSquare48.setText(num2);}
        if(number_Choose == 49){Form_Main.btnSquare49.setText(num2);}if(number_Choose == 50){Form_Main.btnSquare50.setText(num2);}
        if(number_Choose == 51){Form_Main.btnSquare51.setText(num2);}if(number_Choose == 52){Form_Main.btnSquare52.setText(num2);}
        if(number_Choose == 53){Form_Main.btnSquare53.setText(num2);}if(number_Choose == 54){Form_Main.btnSquare54.setText(num2);}
        
        if(number_Choose == 11){Form_Main.btnSquare11.setText(num2);}if(number_Choose == 55){Form_Main.btnSquare55.setText(num2);}
        if(number_Choose == 56){Form_Main.btnSquare56.setText(num2);}if(number_Choose == 57){Form_Main.btnSquare57.setText(num2);}
        if(number_Choose == 58){Form_Main.btnSquare58.setText(num2);}if(number_Choose == 59){Form_Main.btnSquare59.setText(num2);}
        
        if(number_Choose == 6){Form_Main.jButton6.setText(num2);}if(number_Choose == 60){Form_Main.btnSquare60.setText(num2);}
        if(number_Choose == 61){Form_Main.btnSquare61.setText(num2);}if(number_Choose == 62){Form_Main.btnSquare62.setText(num2);}
        if(number_Choose == 63){Form_Main.btnSquare63.setText(num2);}if(number_Choose == 64){Form_Main.btnSquare64.setText(num2);}
        if(number_Choose == 65){Form_Main.btnSquare65.setText(num2);}if(number_Choose == 66){Form_Main.btnSquare66.setText(num2);}
        if(number_Choose == 67){Form_Main.btnSquare67.setText(num2);}if(number_Choose == 68){Form_Main.btnSquare68.setText(num2);}
        if(number_Choose == 69){Form_Main.btnSquare69.setText(num2);}
        
        if(number_Choose == 19){Form_Main.btnSquare19.setText(num2);}if(number_Choose == 70){Form_Main.btnSquare70.setText(num2);}
        if(number_Choose == 71){Form_Main.btnSquare71.setText(num2);}if(number_Choose == 72){Form_Main.btnSquare72.setText(num2);}
        if(number_Choose == 73){Form_Main.btnSquare73.setText(num2);}if(number_Choose == 74){Form_Main.btnSquare74.setText(num2);}
        if(number_Choose == 75){Form_Main.btnSquare75.setText(num2);}if(number_Choose == 76){Form_Main.btnSquare76.setText(num2);}
        if(number_Choose == 77){Form_Main.btnSquare77.setText(num2);}if(number_Choose == 78){Form_Main.btnSquare78.setText(num2);}
        if(number_Choose == 79){Form_Main.btnSquare79.setText(num2);}
        
        if(number_Choose == 20){Form_Main.btnSquare20.setText(num2);}if(number_Choose == 80){Form_Main.btnSquare80.setText(num2);}
        if(number_Choose == 81){Form_Main.btnSquare81.setText(num2);}
        
        if(number_Choose == 21){Form_Main.btnSquare21.setText(num2);}
        if(number_Choose == 12){Form_Main.btnSquare12.setText(num2);}
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String num3 ="3";
        if(number_Choose == 1){Form_Main.btnSquare1.setText(num3);}if(number_Choose == 4){Form_Main.btnSquare4.setText(num3);}
        if(number_Choose == 5){Form_Main.btnSquare5.setText(num3);}if(number_Choose == 6){Form_Main.btnSquare6.setText(num3);}
        if(number_Choose == 13){Form_Main.btnSquare13.setText(num3);}if(number_Choose == 14){Form_Main.btnSquare14.setText(num3);}
        if(number_Choose == 15){Form_Main.btnSquare15.setText(num3);}if(number_Choose == 22){Form_Main.btnSquare22.setText(num3);}
        if(number_Choose == 23){Form_Main.btnSquare23.setText(num3);}if(number_Choose == 24){Form_Main.btnSquare24.setText(num3);}
        if(number_Choose == 7){Form_Main.btnSquare7.setText(num3);}
        
        if(number_Choose == 2){Form_Main.btnSquare2.setText(num3);}if(number_Choose == 8){Form_Main.btnSquare8.setText(num3);}
        if(number_Choose == 9){Form_Main.btnSquare9.setText(num3);}if(number_Choose == 16){Form_Main.btnSquare16.setText(num3);}
        if(number_Choose == 17){Form_Main.btnSquare17.setText(num3);}if(number_Choose == 18){Form_Main.btnSquare18.setText(num3);}
        if(number_Choose == 25){Form_Main.btnSquare25.setText(num3);}if(number_Choose == 26){Form_Main.btnSquare26.setText(num3);}
        if(number_Choose == 27){Form_Main.btnSquare27.setText(num3);}if(number_Choose == 28){Form_Main.btnSquare28.setText(num3);}
        if(number_Choose == 29){Form_Main.btnSquare29.setText(num3);}
        
        if(number_Choose == 3){Form_Main.btnSquare3.setText(num3);}if(number_Choose == 30){Form_Main.btnSquare30.setText(num3);}
        if(number_Choose == 31){Form_Main.btnSquare31.setText(num3);}if(number_Choose == 32){Form_Main.btnSquare32.setText(num3);}
        if(number_Choose == 33){Form_Main.btnSquare33.setText(num3);}if(number_Choose == 34){Form_Main.btnSquare34.setText(num3);}
        if(number_Choose == 35){Form_Main.btnSquare35.setText(num3);}if(number_Choose == 36){Form_Main.btnSquare36.setText(num3);}
        if(number_Choose == 37){Form_Main.btnSquare37.setText(num3);}if(number_Choose == 38){Form_Main.btnSquare38.setText(num3);}
        if(number_Choose == 39){Form_Main.btnSquare39.setText(num3);}
        
        if(number_Choose == 40){Form_Main.btnSquare40.setText(num3);}if(number_Choose == 41){Form_Main.btnSquare41.setText(num3);}
        if(number_Choose == 42){Form_Main.btnSquare42.setText(num3);}if(number_Choose == 10){Form_Main.btnSquare10.setText(num3);}
        if(number_Choose == 43){Form_Main.btnSquare43.setText(num3);}if(number_Choose == 44){Form_Main.btnSquare44.setText(num3);}
        if(number_Choose == 45){Form_Main.btnSquare45.setText(num3);}if(number_Choose == 46){Form_Main.btnSquare46.setText(num3);}
        if(number_Choose == 47){Form_Main.btnSquare47.setText(num3);}if(number_Choose == 48){Form_Main.btnSquare48.setText(num3);}
        if(number_Choose == 49){Form_Main.btnSquare49.setText(num3);}if(number_Choose == 50){Form_Main.btnSquare50.setText(num3);}
        if(number_Choose == 51){Form_Main.btnSquare51.setText(num3);}if(number_Choose == 52){Form_Main.btnSquare52.setText(num3);}
        if(number_Choose == 53){Form_Main.btnSquare53.setText(num3);}if(number_Choose == 54){Form_Main.btnSquare54.setText(num3);}
        
        if(number_Choose == 11){Form_Main.btnSquare11.setText(num3);}if(number_Choose == 55){Form_Main.btnSquare55.setText(num3);}
        if(number_Choose == 56){Form_Main.btnSquare56.setText(num3);}if(number_Choose == 57){Form_Main.btnSquare57.setText(num3);}
        if(number_Choose == 58){Form_Main.btnSquare58.setText(num3);}if(number_Choose == 59){Form_Main.btnSquare59.setText(num3);}
        
        if(number_Choose == 6){Form_Main.jButton6.setText(num3);}if(number_Choose == 60){Form_Main.btnSquare60.setText(num3);}
        if(number_Choose == 61){Form_Main.btnSquare61.setText(num3);}if(number_Choose == 62){Form_Main.btnSquare62.setText(num3);}
        if(number_Choose == 63){Form_Main.btnSquare63.setText(num3);}if(number_Choose == 64){Form_Main.btnSquare64.setText(num3);}
        if(number_Choose == 65){Form_Main.btnSquare65.setText(num3);}if(number_Choose == 66){Form_Main.btnSquare66.setText(num3);}
        if(number_Choose == 67){Form_Main.btnSquare67.setText(num3);}if(number_Choose == 68){Form_Main.btnSquare68.setText(num3);}
        if(number_Choose == 69){Form_Main.btnSquare69.setText(num3);}
        
        if(number_Choose == 19){Form_Main.btnSquare19.setText(num3);}if(number_Choose == 70){Form_Main.btnSquare70.setText(num3);}
        if(number_Choose == 71){Form_Main.btnSquare71.setText(num3);}if(number_Choose == 72){Form_Main.btnSquare72.setText(num3);}
        if(number_Choose == 73){Form_Main.btnSquare73.setText(num3);}if(number_Choose == 74){Form_Main.btnSquare74.setText(num3);}
        if(number_Choose == 75){Form_Main.btnSquare75.setText(num3);}if(number_Choose == 76){Form_Main.btnSquare76.setText(num3);}
        if(number_Choose == 77){Form_Main.btnSquare77.setText(num3);}if(number_Choose == 78){Form_Main.btnSquare78.setText(num3);}
        if(number_Choose == 79){Form_Main.btnSquare79.setText(num3);}
        
        if(number_Choose == 20){Form_Main.btnSquare20.setText(num3);}if(number_Choose == 80){Form_Main.btnSquare80.setText(num3);}
        if(number_Choose == 81){Form_Main.btnSquare81.setText(num3);}
        
        if(number_Choose == 21){Form_Main.btnSquare21.setText(num3);}
        if(number_Choose == 12){Form_Main.btnSquare12.setText(num3);}
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String num4 = "4";
        if(number_Choose == 1){Form_Main.btnSquare1.setText(num4);}if(number_Choose == 4){Form_Main.btnSquare4.setText(num4);}
        if(number_Choose == 5){Form_Main.btnSquare5.setText(num4);}if(number_Choose == 6){Form_Main.btnSquare6.setText(num4);}
        if(number_Choose == 13){Form_Main.btnSquare13.setText(num4);}if(number_Choose == 14){Form_Main.btnSquare14.setText(num4);}
        if(number_Choose == 15){Form_Main.btnSquare15.setText(num4);}if(number_Choose == 22){Form_Main.btnSquare22.setText(num4);}
        if(number_Choose == 23){Form_Main.btnSquare23.setText(num4);}if(number_Choose == 24){Form_Main.btnSquare24.setText(num4);}
        if(number_Choose == 7){Form_Main.btnSquare7.setText(num4);}
        
        if(number_Choose == 2){Form_Main.btnSquare2.setText(num4);}if(number_Choose == 8){Form_Main.btnSquare8.setText(num4);}
        if(number_Choose == 9){Form_Main.btnSquare9.setText(num4);}if(number_Choose == 16){Form_Main.btnSquare16.setText(num4);}
        if(number_Choose == 17){Form_Main.btnSquare17.setText(num4);}if(number_Choose == 18){Form_Main.btnSquare18.setText(num4);}
        if(number_Choose == 25){Form_Main.btnSquare25.setText(num4);}if(number_Choose == 26){Form_Main.btnSquare26.setText(num4);}
        if(number_Choose == 27){Form_Main.btnSquare27.setText(num4);}if(number_Choose == 28){Form_Main.btnSquare28.setText(num4);}
        if(number_Choose == 29){Form_Main.btnSquare29.setText(num4);}
        
        if(number_Choose == 3){Form_Main.btnSquare3.setText(num4);}if(number_Choose == 30){Form_Main.btnSquare30.setText(num4);}
        if(number_Choose == 31){Form_Main.btnSquare31.setText(num4);}if(number_Choose == 32){Form_Main.btnSquare32.setText(num4);}
        if(number_Choose == 33){Form_Main.btnSquare33.setText(num4);}if(number_Choose == 34){Form_Main.btnSquare34.setText(num4);}
        if(number_Choose == 35){Form_Main.btnSquare35.setText(num4);}if(number_Choose == 36){Form_Main.btnSquare36.setText(num4);}
        if(number_Choose == 37){Form_Main.btnSquare37.setText(num4);}if(number_Choose == 38){Form_Main.btnSquare38.setText(num4);}
        if(number_Choose == 39){Form_Main.btnSquare39.setText(num4);}
        
        if(number_Choose == 40){Form_Main.btnSquare40.setText(num4);}if(number_Choose == 41){Form_Main.btnSquare41.setText(num4);}
        if(number_Choose == 42){Form_Main.btnSquare42.setText(num4);}if(number_Choose == 10){Form_Main.btnSquare10.setText(num4);}
        if(number_Choose == 43){Form_Main.btnSquare43.setText(num4);}if(number_Choose == 44){Form_Main.btnSquare44.setText(num4);}
        if(number_Choose == 45){Form_Main.btnSquare45.setText(num4);}if(number_Choose == 46){Form_Main.btnSquare46.setText(num4);}
        if(number_Choose == 47){Form_Main.btnSquare47.setText(num4);}if(number_Choose == 48){Form_Main.btnSquare48.setText(num4);}
        if(number_Choose == 49){Form_Main.btnSquare49.setText(num4);}if(number_Choose == 50){Form_Main.btnSquare50.setText(num4);}
        if(number_Choose == 51){Form_Main.btnSquare51.setText(num4);}if(number_Choose == 52){Form_Main.btnSquare52.setText(num4);}
        if(number_Choose == 53){Form_Main.btnSquare53.setText(num4);}if(number_Choose == 54){Form_Main.btnSquare54.setText(num4);}
        
        if(number_Choose == 11){Form_Main.btnSquare11.setText(num4);}if(number_Choose == 55){Form_Main.btnSquare55.setText(num4);}
        if(number_Choose == 56){Form_Main.btnSquare56.setText(num4);}if(number_Choose == 57){Form_Main.btnSquare57.setText(num4);}
        if(number_Choose == 58){Form_Main.btnSquare58.setText(num4);}if(number_Choose == 59){Form_Main.btnSquare59.setText(num4);}
        
        if(number_Choose == 6){Form_Main.jButton6.setText(num4);}if(number_Choose == 60){Form_Main.btnSquare60.setText(num4);}
        if(number_Choose == 61){Form_Main.btnSquare61.setText(num4);}if(number_Choose == 62){Form_Main.btnSquare62.setText(num4);}
        if(number_Choose == 63){Form_Main.btnSquare63.setText(num4);}if(number_Choose == 64){Form_Main.btnSquare64.setText(num4);}
        if(number_Choose == 65){Form_Main.btnSquare65.setText(num4);}if(number_Choose == 66){Form_Main.btnSquare66.setText(num4);}
        if(number_Choose == 67){Form_Main.btnSquare67.setText(num4);}if(number_Choose == 68){Form_Main.btnSquare68.setText(num4);}
        if(number_Choose == 69){Form_Main.btnSquare69.setText(num4);}
        
        if(number_Choose == 19){Form_Main.btnSquare19.setText(num4);}if(number_Choose == 70){Form_Main.btnSquare70.setText(num4);}
        if(number_Choose == 71){Form_Main.btnSquare71.setText(num4);}if(number_Choose == 72){Form_Main.btnSquare72.setText(num4);}
        if(number_Choose == 73){Form_Main.btnSquare73.setText(num4);}if(number_Choose == 74){Form_Main.btnSquare74.setText(num4);}
        if(number_Choose == 75){Form_Main.btnSquare75.setText(num4);}if(number_Choose == 76){Form_Main.btnSquare76.setText(num4);}
        if(number_Choose == 77){Form_Main.btnSquare77.setText(num4);}if(number_Choose == 78){Form_Main.btnSquare78.setText(num4);}
        if(number_Choose == 79){Form_Main.btnSquare79.setText(num4);}
        
        if(number_Choose == 20){Form_Main.btnSquare20.setText(num4);}if(number_Choose == 80){Form_Main.btnSquare80.setText(num4);}
        if(number_Choose == 81){Form_Main.btnSquare81.setText(num4);}
        
        if(number_Choose == 21){Form_Main.btnSquare21.setText(num4);}
        if(number_Choose == 12){Form_Main.btnSquare12.setText(num4);}
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String num5 ="5";
        if(number_Choose == 1){Form_Main.btnSquare1.setText(num5);}if(number_Choose == 4){Form_Main.btnSquare4.setText(num5);}
        if(number_Choose == 5){Form_Main.btnSquare5.setText(num5);}if(number_Choose == 6){Form_Main.btnSquare6.setText(num5);}
        if(number_Choose == 13){Form_Main.btnSquare13.setText(num5);}if(number_Choose == 14){Form_Main.btnSquare14.setText(num5);}
        if(number_Choose == 15){Form_Main.btnSquare15.setText(num5);}if(number_Choose == 22){Form_Main.btnSquare22.setText(num5);}
        if(number_Choose == 23){Form_Main.btnSquare23.setText(num5);}if(number_Choose == 24){Form_Main.btnSquare24.setText(num5);}
        if(number_Choose == 7){Form_Main.btnSquare7.setText(num5);}
        
        if(number_Choose == 2){Form_Main.btnSquare2.setText(num5);}if(number_Choose == 8){Form_Main.btnSquare8.setText(num5);}
        if(number_Choose == 9){Form_Main.btnSquare9.setText(num5);}if(number_Choose == 16){Form_Main.btnSquare16.setText(num5);}
        if(number_Choose == 17){Form_Main.btnSquare17.setText(num5);}if(number_Choose == 18){Form_Main.btnSquare18.setText(num5);}
        if(number_Choose == 25){Form_Main.btnSquare25.setText(num5);}if(number_Choose == 26){Form_Main.btnSquare26.setText(num5);}
        if(number_Choose == 27){Form_Main.btnSquare27.setText(num5);}if(number_Choose == 28){Form_Main.btnSquare28.setText(num5);}
        if(number_Choose == 29){Form_Main.btnSquare29.setText(num5);}
        
        if(number_Choose == 3){Form_Main.btnSquare3.setText(num5);}if(number_Choose == 30){Form_Main.btnSquare30.setText(num5);}
        if(number_Choose == 31){Form_Main.btnSquare31.setText(num5);}if(number_Choose == 32){Form_Main.btnSquare32.setText(num5);}
        if(number_Choose == 33){Form_Main.btnSquare33.setText(num5);}if(number_Choose == 34){Form_Main.btnSquare34.setText(num5);}
        if(number_Choose == 35){Form_Main.btnSquare35.setText(num5);}if(number_Choose == 36){Form_Main.btnSquare36.setText(num5);}
        if(number_Choose == 37){Form_Main.btnSquare37.setText(num5);}if(number_Choose == 38){Form_Main.btnSquare38.setText(num5);}
        if(number_Choose == 39){Form_Main.btnSquare39.setText(num5);}
        
        if(number_Choose == 40){Form_Main.btnSquare40.setText(num5);}if(number_Choose == 41){Form_Main.btnSquare41.setText(num5);}
        if(number_Choose == 42){Form_Main.btnSquare42.setText(num5);}if(number_Choose == 10){Form_Main.btnSquare10.setText(num5);}
        if(number_Choose == 43){Form_Main.btnSquare43.setText(num5);}if(number_Choose == 44){Form_Main.btnSquare44.setText(num5);}
        if(number_Choose == 45){Form_Main.btnSquare45.setText(num5);}if(number_Choose == 46){Form_Main.btnSquare46.setText(num5);}
        if(number_Choose == 47){Form_Main.btnSquare47.setText(num5);}if(number_Choose == 48){Form_Main.btnSquare48.setText(num5);}
        if(number_Choose == 49){Form_Main.btnSquare49.setText(num5);}if(number_Choose == 50){Form_Main.btnSquare50.setText(num5);}
        if(number_Choose == 51){Form_Main.btnSquare51.setText(num5);}if(number_Choose == 52){Form_Main.btnSquare52.setText(num5);}
        if(number_Choose == 53){Form_Main.btnSquare53.setText(num5);}if(number_Choose == 54){Form_Main.btnSquare54.setText(num5);}
        
        if(number_Choose == 11){Form_Main.btnSquare11.setText(num5);}if(number_Choose == 55){Form_Main.btnSquare55.setText(num5);}
        if(number_Choose == 56){Form_Main.btnSquare56.setText(num5);}if(number_Choose == 57){Form_Main.btnSquare57.setText(num5);}
        if(number_Choose == 58){Form_Main.btnSquare58.setText(num5);}if(number_Choose == 59){Form_Main.btnSquare59.setText(num5);}
        
        if(number_Choose == 6){Form_Main.jButton6.setText(num5);}if(number_Choose == 60){Form_Main.btnSquare60.setText(num5);}
        if(number_Choose == 61){Form_Main.btnSquare61.setText(num5);}if(number_Choose == 62){Form_Main.btnSquare62.setText(num5);}
        if(number_Choose == 63){Form_Main.btnSquare63.setText(num5);}if(number_Choose == 64){Form_Main.btnSquare64.setText(num5);}
        if(number_Choose == 65){Form_Main.btnSquare65.setText(num5);}if(number_Choose == 66){Form_Main.btnSquare66.setText(num5);}
        if(number_Choose == 67){Form_Main.btnSquare67.setText(num5);}if(number_Choose == 68){Form_Main.btnSquare68.setText(num5);}
        if(number_Choose == 69){Form_Main.btnSquare69.setText(num5);}
        
        if(number_Choose == 19){Form_Main.btnSquare19.setText(num5);}if(number_Choose == 70){Form_Main.btnSquare70.setText(num5);}
        if(number_Choose == 71){Form_Main.btnSquare71.setText(num5);}if(number_Choose == 72){Form_Main.btnSquare72.setText(num5);}
        if(number_Choose == 73){Form_Main.btnSquare73.setText(num5);}if(number_Choose == 74){Form_Main.btnSquare74.setText(num5);}
        if(number_Choose == 75){Form_Main.btnSquare75.setText(num5);}if(number_Choose == 76){Form_Main.btnSquare76.setText(num5);}
        if(number_Choose == 77){Form_Main.btnSquare77.setText(num5);}if(number_Choose == 78){Form_Main.btnSquare78.setText(num5);}
        if(number_Choose == 79){Form_Main.btnSquare79.setText(num5);}
        
        if(number_Choose == 20){Form_Main.btnSquare20.setText(num5);}if(number_Choose == 80){Form_Main.btnSquare80.setText(num5);}
        if(number_Choose == 81){Form_Main.btnSquare81.setText(num5);}
        
        if(number_Choose == 21){Form_Main.btnSquare21.setText(num5);}
        if(number_Choose == 12){Form_Main.btnSquare12.setText(num5);}
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String num6="6";
        if(number_Choose == 1){Form_Main.btnSquare1.setText(num6);}if(number_Choose == 4){Form_Main.btnSquare4.setText(num6);}
        if(number_Choose == 5){Form_Main.btnSquare5.setText(num6);}if(number_Choose == 6){Form_Main.btnSquare6.setText(num6);}
        if(number_Choose == 13){Form_Main.btnSquare13.setText(num6);}if(number_Choose == 14){Form_Main.btnSquare14.setText(num6);}
        if(number_Choose == 15){Form_Main.btnSquare15.setText(num6);}if(number_Choose == 22){Form_Main.btnSquare22.setText(num6);}
        if(number_Choose == 23){Form_Main.btnSquare23.setText(num6);}if(number_Choose == 24){Form_Main.btnSquare24.setText(num6);}
        if(number_Choose == 7){Form_Main.btnSquare7.setText(num6);}
        
        if(number_Choose == 2){Form_Main.btnSquare2.setText(num6);}if(number_Choose == 8){Form_Main.btnSquare8.setText(num6);}
        if(number_Choose == 9){Form_Main.btnSquare9.setText(num6);}if(number_Choose == 16){Form_Main.btnSquare16.setText(num6);}
        if(number_Choose == 17){Form_Main.btnSquare17.setText(num6);}if(number_Choose == 18){Form_Main.btnSquare18.setText(num6);}
        if(number_Choose == 25){Form_Main.btnSquare25.setText(num6);}if(number_Choose == 26){Form_Main.btnSquare26.setText(num6);}
        if(number_Choose == 27){Form_Main.btnSquare27.setText(num6);}if(number_Choose == 28){Form_Main.btnSquare28.setText(num6);}
        if(number_Choose == 29){Form_Main.btnSquare29.setText(num6);}
        
        if(number_Choose == 3){Form_Main.btnSquare3.setText(num6);}if(number_Choose == 30){Form_Main.btnSquare30.setText(num6);}
        if(number_Choose == 31){Form_Main.btnSquare31.setText(num6);}if(number_Choose == 32){Form_Main.btnSquare32.setText(num6);}
        if(number_Choose == 33){Form_Main.btnSquare33.setText(num6);}if(number_Choose == 34){Form_Main.btnSquare34.setText(num6);}
        if(number_Choose == 35){Form_Main.btnSquare35.setText(num6);}if(number_Choose == 36){Form_Main.btnSquare36.setText(num6);}
        if(number_Choose == 37){Form_Main.btnSquare37.setText(num6);}if(number_Choose == 38){Form_Main.btnSquare38.setText(num6);}
        if(number_Choose == 39){Form_Main.btnSquare39.setText(num6);}
        
        if(number_Choose == 40){Form_Main.btnSquare40.setText(num6);}if(number_Choose == 41){Form_Main.btnSquare41.setText(num6);}
        if(number_Choose == 42){Form_Main.btnSquare42.setText(num6);}if(number_Choose == 10){Form_Main.btnSquare10.setText(num6);}
        if(number_Choose == 43){Form_Main.btnSquare43.setText(num6);}if(number_Choose == 44){Form_Main.btnSquare44.setText(num6);}
        if(number_Choose == 45){Form_Main.btnSquare45.setText(num6);}if(number_Choose == 46){Form_Main.btnSquare46.setText(num6);}
        if(number_Choose == 47){Form_Main.btnSquare47.setText(num6);}if(number_Choose == 48){Form_Main.btnSquare48.setText(num6);}
        if(number_Choose == 49){Form_Main.btnSquare49.setText(num6);}if(number_Choose == 50){Form_Main.btnSquare50.setText(num6);}
        if(number_Choose == 51){Form_Main.btnSquare51.setText(num6);}if(number_Choose == 52){Form_Main.btnSquare52.setText(num6);}
        if(number_Choose == 53){Form_Main.btnSquare53.setText(num6);}if(number_Choose == 54){Form_Main.btnSquare54.setText(num6);}
        
        if(number_Choose == 11){Form_Main.btnSquare11.setText(num6);}if(number_Choose == 55){Form_Main.btnSquare55.setText(num6);}
        if(number_Choose == 56){Form_Main.btnSquare56.setText(num6);}if(number_Choose == 57){Form_Main.btnSquare57.setText(num6);}
        if(number_Choose == 58){Form_Main.btnSquare58.setText(num6);}if(number_Choose == 59){Form_Main.btnSquare59.setText(num6);}
        
        if(number_Choose == 6){Form_Main.jButton6.setText(num6);}if(number_Choose == 60){Form_Main.btnSquare60.setText(num6);}
        if(number_Choose == 61){Form_Main.btnSquare61.setText(num6);}if(number_Choose == 62){Form_Main.btnSquare62.setText(num6);}
        if(number_Choose == 63){Form_Main.btnSquare63.setText(num6);}if(number_Choose == 64){Form_Main.btnSquare64.setText(num6);}
        if(number_Choose == 65){Form_Main.btnSquare65.setText(num6);}if(number_Choose == 66){Form_Main.btnSquare66.setText(num6);}
        if(number_Choose == 67){Form_Main.btnSquare67.setText(num6);}if(number_Choose == 68){Form_Main.btnSquare68.setText(num6);}
        if(number_Choose == 69){Form_Main.btnSquare69.setText(num6);}
        
        if(number_Choose == 19){Form_Main.btnSquare19.setText(num6);}if(number_Choose == 70){Form_Main.btnSquare70.setText(num6);}
        if(number_Choose == 71){Form_Main.btnSquare71.setText(num6);}if(number_Choose == 72){Form_Main.btnSquare72.setText(num6);}
        if(number_Choose == 73){Form_Main.btnSquare73.setText(num6);}if(number_Choose == 74){Form_Main.btnSquare74.setText(num6);}
        if(number_Choose == 75){Form_Main.btnSquare75.setText(num6);}if(number_Choose == 76){Form_Main.btnSquare76.setText(num6);}
        if(number_Choose == 77){Form_Main.btnSquare77.setText(num6);}if(number_Choose == 78){Form_Main.btnSquare78.setText(num6);}
        if(number_Choose == 79){Form_Main.btnSquare79.setText(num6);}
        
        if(number_Choose == 20){Form_Main.btnSquare20.setText(num6);}if(number_Choose == 80){Form_Main.btnSquare80.setText(num6);}
        if(number_Choose == 81){Form_Main.btnSquare81.setText(num6);}
        
        if(number_Choose == 21){Form_Main.btnSquare21.setText(num6);}
        if(number_Choose == 12){Form_Main.btnSquare12.setText(num6);}
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String num7 = "7";
        if(number_Choose == 1){Form_Main.btnSquare1.setText(num7);}if(number_Choose == 4){Form_Main.btnSquare4.setText(num7);}
        if(number_Choose == 5){Form_Main.btnSquare5.setText(num7);}if(number_Choose == 6){Form_Main.btnSquare6.setText(num7);}
        if(number_Choose == 13){Form_Main.btnSquare13.setText(num7);}if(number_Choose == 14){Form_Main.btnSquare14.setText(num7);}
        if(number_Choose == 15){Form_Main.btnSquare15.setText(num7);}if(number_Choose == 22){Form_Main.btnSquare22.setText(num7);}
        if(number_Choose == 23){Form_Main.btnSquare23.setText(num7);}if(number_Choose == 24){Form_Main.btnSquare24.setText(num7);}
        if(number_Choose == 7){Form_Main.btnSquare7.setText(num7);}
        
        if(number_Choose == 2){Form_Main.btnSquare2.setText(num7);}if(number_Choose == 8){Form_Main.btnSquare8.setText(num7);}
        if(number_Choose == 9){Form_Main.btnSquare9.setText(num7);}if(number_Choose == 16){Form_Main.btnSquare16.setText(num7);}
        if(number_Choose == 17){Form_Main.btnSquare17.setText(num7);}if(number_Choose == 18){Form_Main.btnSquare18.setText(num7);}
        if(number_Choose == 25){Form_Main.btnSquare25.setText(num7);}if(number_Choose == 26){Form_Main.btnSquare26.setText(num7);}
        if(number_Choose == 27){Form_Main.btnSquare27.setText(num7);}if(number_Choose == 28){Form_Main.btnSquare28.setText(num7);}
        if(number_Choose == 29){Form_Main.btnSquare29.setText(num7);}
        
        if(number_Choose == 3){Form_Main.btnSquare3.setText(num7);}if(number_Choose == 30){Form_Main.btnSquare30.setText(num7);}
        if(number_Choose == 31){Form_Main.btnSquare31.setText(num7);}if(number_Choose == 32){Form_Main.btnSquare32.setText(num7);}
        if(number_Choose == 33){Form_Main.btnSquare33.setText(num7);}if(number_Choose == 34){Form_Main.btnSquare34.setText(num7);}
        if(number_Choose == 35){Form_Main.btnSquare35.setText(num7);}if(number_Choose == 36){Form_Main.btnSquare36.setText(num7);}
        if(number_Choose == 37){Form_Main.btnSquare37.setText(num7);}if(number_Choose == 38){Form_Main.btnSquare38.setText(num7);}
        if(number_Choose == 39){Form_Main.btnSquare39.setText(num7);}
        
        if(number_Choose == 40){Form_Main.btnSquare40.setText(num7);}if(number_Choose == 41){Form_Main.btnSquare41.setText(num7);}
        if(number_Choose == 42){Form_Main.btnSquare42.setText(num7);}if(number_Choose == 10){Form_Main.btnSquare10.setText(num7);}
        if(number_Choose == 43){Form_Main.btnSquare43.setText(num7);}if(number_Choose == 44){Form_Main.btnSquare44.setText(num7);}
        if(number_Choose == 45){Form_Main.btnSquare45.setText(num7);}if(number_Choose == 46){Form_Main.btnSquare46.setText(num7);}
        if(number_Choose == 47){Form_Main.btnSquare47.setText(num7);}if(number_Choose == 48){Form_Main.btnSquare48.setText(num7);}
        if(number_Choose == 49){Form_Main.btnSquare49.setText(num7);}if(number_Choose == 50){Form_Main.btnSquare50.setText(num7);}
        if(number_Choose == 51){Form_Main.btnSquare51.setText(num7);}if(number_Choose == 52){Form_Main.btnSquare52.setText(num7);}
        if(number_Choose == 53){Form_Main.btnSquare53.setText(num7);}if(number_Choose == 54){Form_Main.btnSquare54.setText(num7);}
        
        if(number_Choose == 11){Form_Main.btnSquare11.setText(num7);}if(number_Choose == 55){Form_Main.btnSquare55.setText(num7);}
        if(number_Choose == 56){Form_Main.btnSquare56.setText(num7);}if(number_Choose == 57){Form_Main.btnSquare57.setText(num7);}
        if(number_Choose == 58){Form_Main.btnSquare58.setText(num7);}if(number_Choose == 59){Form_Main.btnSquare59.setText(num7);}
        
        if(number_Choose == 6){Form_Main.jButton6.setText(num7);}if(number_Choose == 60){Form_Main.btnSquare60.setText(num7);}
        if(number_Choose == 61){Form_Main.btnSquare61.setText(num7);}if(number_Choose == 62){Form_Main.btnSquare62.setText(num7);}
        if(number_Choose == 63){Form_Main.btnSquare63.setText(num7);}if(number_Choose == 64){Form_Main.btnSquare64.setText(num7);}
        if(number_Choose == 65){Form_Main.btnSquare65.setText(num7);}if(number_Choose == 66){Form_Main.btnSquare66.setText(num7);}
        if(number_Choose == 67){Form_Main.btnSquare67.setText(num7);}if(number_Choose == 68){Form_Main.btnSquare68.setText(num7);}
        if(number_Choose == 69){Form_Main.btnSquare69.setText(num7);}
        
        if(number_Choose == 19){Form_Main.btnSquare19.setText(num7);}if(number_Choose == 70){Form_Main.btnSquare70.setText(num7);}
        if(number_Choose == 71){Form_Main.btnSquare71.setText(num7);}if(number_Choose == 72){Form_Main.btnSquare72.setText(num7);}
        if(number_Choose == 73){Form_Main.btnSquare73.setText(num7);}if(number_Choose == 74){Form_Main.btnSquare74.setText(num7);}
        if(number_Choose == 75){Form_Main.btnSquare75.setText(num7);}if(number_Choose == 76){Form_Main.btnSquare76.setText(num7);}
        if(number_Choose == 77){Form_Main.btnSquare77.setText(num7);}if(number_Choose == 78){Form_Main.btnSquare78.setText(num7);}
        if(number_Choose == 79){Form_Main.btnSquare79.setText(num7);}
        
        if(number_Choose == 20){Form_Main.btnSquare20.setText(num7);}if(number_Choose == 80){Form_Main.btnSquare80.setText(num7);}
        if(number_Choose == 81){Form_Main.btnSquare81.setText(num7);}
        
        if(number_Choose == 21){Form_Main.btnSquare21.setText(num7);}
        if(number_Choose == 12){Form_Main.btnSquare12.setText(num7);}
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String num8 = "8";
        if(number_Choose == 1){Form_Main.btnSquare1.setText(num8);}if(number_Choose == 4){Form_Main.btnSquare4.setText(num8);}
        if(number_Choose == 5){Form_Main.btnSquare5.setText(num8);}if(number_Choose == 6){Form_Main.btnSquare6.setText(num8);}
        if(number_Choose == 13){Form_Main.btnSquare13.setText(num8);}if(number_Choose == 14){Form_Main.btnSquare14.setText(num8);}
        if(number_Choose == 15){Form_Main.btnSquare15.setText(num8);}if(number_Choose == 22){Form_Main.btnSquare22.setText(num8);}
        if(number_Choose == 23){Form_Main.btnSquare23.setText(num8);}if(number_Choose == 24){Form_Main.btnSquare24.setText(num8);}
        if(number_Choose == 7){Form_Main.btnSquare7.setText(num8);}
        
        if(number_Choose == 2){Form_Main.btnSquare2.setText(num8);}if(number_Choose == 8){Form_Main.btnSquare8.setText(num8);}
        if(number_Choose == 9){Form_Main.btnSquare9.setText(num8);}if(number_Choose == 16){Form_Main.btnSquare16.setText(num8);}
        if(number_Choose == 17){Form_Main.btnSquare17.setText(num8);}if(number_Choose == 18){Form_Main.btnSquare18.setText(num8);}
        if(number_Choose == 25){Form_Main.btnSquare25.setText(num8);}if(number_Choose == 26){Form_Main.btnSquare26.setText(num8);}
        if(number_Choose == 27){Form_Main.btnSquare27.setText(num8);}if(number_Choose == 28){Form_Main.btnSquare28.setText(num8);}
        if(number_Choose == 29){Form_Main.btnSquare29.setText(num8);}
        
        if(number_Choose == 3){Form_Main.btnSquare3.setText(num8);}if(number_Choose == 30){Form_Main.btnSquare30.setText(num8);}
        if(number_Choose == 31){Form_Main.btnSquare31.setText(num8);}if(number_Choose == 32){Form_Main.btnSquare32.setText(num8);}
        if(number_Choose == 33){Form_Main.btnSquare33.setText(num8);}if(number_Choose == 34){Form_Main.btnSquare34.setText(num8);}
        if(number_Choose == 35){Form_Main.btnSquare35.setText(num8);}if(number_Choose == 36){Form_Main.btnSquare36.setText(num8);}
        if(number_Choose == 37){Form_Main.btnSquare37.setText(num8);}if(number_Choose == 38){Form_Main.btnSquare38.setText(num8);}
        if(number_Choose == 39){Form_Main.btnSquare39.setText(num8);}
        
        if(number_Choose == 40){Form_Main.btnSquare40.setText(num8);}if(number_Choose == 41){Form_Main.btnSquare41.setText(num8);}
        if(number_Choose == 42){Form_Main.btnSquare42.setText(num8);}if(number_Choose == 10){Form_Main.btnSquare10.setText(num8);}
        if(number_Choose == 43){Form_Main.btnSquare43.setText(num8);}if(number_Choose == 44){Form_Main.btnSquare44.setText(num8);}
        if(number_Choose == 45){Form_Main.btnSquare45.setText(num8);}if(number_Choose == 46){Form_Main.btnSquare46.setText(num8);}
        if(number_Choose == 47){Form_Main.btnSquare47.setText(num8);}if(number_Choose == 48){Form_Main.btnSquare48.setText(num8);}
        if(number_Choose == 49){Form_Main.btnSquare49.setText(num8);}if(number_Choose == 50){Form_Main.btnSquare50.setText(num8);}
        if(number_Choose == 51){Form_Main.btnSquare51.setText(num8);}if(number_Choose == 52){Form_Main.btnSquare52.setText(num8);}
        if(number_Choose == 53){Form_Main.btnSquare53.setText(num8);}if(number_Choose == 54){Form_Main.btnSquare54.setText(num8);}
        
        if(number_Choose == 11){Form_Main.btnSquare11.setText(num8);}if(number_Choose == 55){Form_Main.btnSquare55.setText(num8);}
        if(number_Choose == 56){Form_Main.btnSquare56.setText(num8);}if(number_Choose == 57){Form_Main.btnSquare57.setText(num8);}
        if(number_Choose == 58){Form_Main.btnSquare58.setText(num8);}if(number_Choose == 59){Form_Main.btnSquare59.setText(num8);}
        
        if(number_Choose == 6){Form_Main.jButton6.setText(num8);}if(number_Choose == 60){Form_Main.btnSquare60.setText(num8);}
        if(number_Choose == 61){Form_Main.btnSquare61.setText(num8);}if(number_Choose == 62){Form_Main.btnSquare62.setText(num8);}
        if(number_Choose == 63){Form_Main.btnSquare63.setText(num8);}if(number_Choose == 64){Form_Main.btnSquare64.setText(num8);}
        if(number_Choose == 65){Form_Main.btnSquare65.setText(num8);}if(number_Choose == 66){Form_Main.btnSquare66.setText(num8);}
        if(number_Choose == 67){Form_Main.btnSquare67.setText(num8);}if(number_Choose == 68){Form_Main.btnSquare68.setText(num8);}
        if(number_Choose == 69){Form_Main.btnSquare69.setText(num8);}
        
        if(number_Choose == 19){Form_Main.btnSquare19.setText(num8);}if(number_Choose == 70){Form_Main.btnSquare70.setText(num8);}
        if(number_Choose == 71){Form_Main.btnSquare71.setText(num8);}if(number_Choose == 72){Form_Main.btnSquare72.setText(num8);}
        if(number_Choose == 73){Form_Main.btnSquare73.setText(num8);}if(number_Choose == 74){Form_Main.btnSquare74.setText(num8);}
        if(number_Choose == 75){Form_Main.btnSquare75.setText(num8);}if(number_Choose == 76){Form_Main.btnSquare76.setText(num8);}
        if(number_Choose == 77){Form_Main.btnSquare77.setText(num8);}if(number_Choose == 78){Form_Main.btnSquare78.setText(num8);}
        if(number_Choose == 79){Form_Main.btnSquare79.setText(num8);}
        
        if(number_Choose == 20){Form_Main.btnSquare20.setText(num8);}if(number_Choose == 80){Form_Main.btnSquare80.setText(num8);}
        if(number_Choose == 81){Form_Main.btnSquare81.setText(num8);}
        
        if(number_Choose == 21){Form_Main.btnSquare21.setText(num8);}
        if(number_Choose == 12){Form_Main.btnSquare12.setText(num8);}
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String num9 = "9";
        if(number_Choose == 1){Form_Main.btnSquare1.setText(num9);}if(number_Choose == 4){Form_Main.btnSquare4.setText(num9);}
        if(number_Choose == 5){Form_Main.btnSquare5.setText(num9);}if(number_Choose == 6){Form_Main.btnSquare6.setText(num9);}
        if(number_Choose == 13){Form_Main.btnSquare13.setText(num9);}if(number_Choose == 14){Form_Main.btnSquare14.setText(num9);}
        if(number_Choose == 15){Form_Main.btnSquare15.setText(num9);}if(number_Choose == 22){Form_Main.btnSquare22.setText(num9);}
        if(number_Choose == 23){Form_Main.btnSquare23.setText(num9);}if(number_Choose == 24){Form_Main.btnSquare24.setText(num9);}
        if(number_Choose == 7){Form_Main.btnSquare7.setText(num9);}
        
        if(number_Choose == 2){Form_Main.btnSquare2.setText(num9);}if(number_Choose == 8){Form_Main.btnSquare8.setText(num9);}
        if(number_Choose == 9){Form_Main.btnSquare9.setText(num9);}if(number_Choose == 16){Form_Main.btnSquare16.setText(num9);}
        if(number_Choose == 17){Form_Main.btnSquare17.setText(num9);}if(number_Choose == 18){Form_Main.btnSquare18.setText(num9);}
        if(number_Choose == 25){Form_Main.btnSquare25.setText(num9);}if(number_Choose == 26){Form_Main.btnSquare26.setText(num9);}
        if(number_Choose == 27){Form_Main.btnSquare27.setText(num9);}if(number_Choose == 28){Form_Main.btnSquare28.setText(num9);}
        if(number_Choose == 29){Form_Main.btnSquare29.setText(num9);}
        
        if(number_Choose == 3){Form_Main.btnSquare3.setText(num9);}if(number_Choose == 30){Form_Main.btnSquare30.setText(num9);}
        if(number_Choose == 31){Form_Main.btnSquare31.setText(num9);}if(number_Choose == 32){Form_Main.btnSquare32.setText(num9);}
        if(number_Choose == 33){Form_Main.btnSquare33.setText(num9);}if(number_Choose == 34){Form_Main.btnSquare34.setText(num9);}
        if(number_Choose == 35){Form_Main.btnSquare35.setText(num9);}if(number_Choose == 36){Form_Main.btnSquare36.setText(num9);}
        if(number_Choose == 37){Form_Main.btnSquare37.setText(num9);}if(number_Choose == 38){Form_Main.btnSquare38.setText(num9);}
        if(number_Choose == 39){Form_Main.btnSquare39.setText(num9);}
        
        if(number_Choose == 40){Form_Main.btnSquare40.setText(num9);}if(number_Choose == 41){Form_Main.btnSquare41.setText(num9);}
        if(number_Choose == 42){Form_Main.btnSquare42.setText(num9);}if(number_Choose == 10){Form_Main.btnSquare10.setText(num9);}
        if(number_Choose == 43){Form_Main.btnSquare43.setText(num9);}if(number_Choose == 44){Form_Main.btnSquare44.setText(num9);}
        if(number_Choose == 45){Form_Main.btnSquare45.setText(num9);}if(number_Choose == 46){Form_Main.btnSquare46.setText(num9);}
        if(number_Choose == 47){Form_Main.btnSquare47.setText(num9);}if(number_Choose == 48){Form_Main.btnSquare48.setText(num9);}
        if(number_Choose == 49){Form_Main.btnSquare49.setText(num9);}if(number_Choose == 50){Form_Main.btnSquare50.setText(num9);}
        if(number_Choose == 51){Form_Main.btnSquare51.setText(num9);}if(number_Choose == 52){Form_Main.btnSquare52.setText(num9);}
        if(number_Choose == 53){Form_Main.btnSquare53.setText(num9);}if(number_Choose == 54){Form_Main.btnSquare54.setText(num9);}
        
        if(number_Choose == 11){Form_Main.btnSquare11.setText(num9);}if(number_Choose == 55){Form_Main.btnSquare55.setText(num9);}
        if(number_Choose == 56){Form_Main.btnSquare56.setText(num9);}if(number_Choose == 57){Form_Main.btnSquare57.setText(num9);}
        if(number_Choose == 58){Form_Main.btnSquare58.setText(num9);}if(number_Choose == 59){Form_Main.btnSquare59.setText(num9);}
        
        if(number_Choose == 6){Form_Main.jButton6.setText(num9);}if(number_Choose == 60){Form_Main.btnSquare60.setText(num9);}
        if(number_Choose == 61){Form_Main.btnSquare61.setText(num9);}if(number_Choose == 62){Form_Main.btnSquare62.setText(num9);}
        if(number_Choose == 63){Form_Main.btnSquare63.setText(num9);}if(number_Choose == 64){Form_Main.btnSquare64.setText(num9);}
        if(number_Choose == 65){Form_Main.btnSquare65.setText(num9);}if(number_Choose == 66){Form_Main.btnSquare66.setText(num9);}
        if(number_Choose == 67){Form_Main.btnSquare67.setText(num9);}if(number_Choose == 68){Form_Main.btnSquare68.setText(num9);}
        if(number_Choose == 69){Form_Main.btnSquare69.setText(num9);}
        
        if(number_Choose == 19){Form_Main.btnSquare19.setText(num9);}if(number_Choose == 70){Form_Main.btnSquare70.setText(num9);}
        if(number_Choose == 71){Form_Main.btnSquare71.setText(num9);}if(number_Choose == 72){Form_Main.btnSquare72.setText(num9);}
        if(number_Choose == 73){Form_Main.btnSquare73.setText(num9);}if(number_Choose == 74){Form_Main.btnSquare74.setText(num9);}
        if(number_Choose == 75){Form_Main.btnSquare75.setText(num9);}if(number_Choose == 76){Form_Main.btnSquare76.setText(num9);}
        if(number_Choose == 77){Form_Main.btnSquare77.setText(num9);}if(number_Choose == 78){Form_Main.btnSquare78.setText(num9);}
        if(number_Choose == 79){Form_Main.btnSquare79.setText(num9);}
        
        if(number_Choose == 20){Form_Main.btnSquare20.setText(num9);}if(number_Choose == 80){Form_Main.btnSquare80.setText(num9);}
        if(number_Choose == 81){Form_Main.btnSquare81.setText(num9);}
        
        if(number_Choose == 21){Form_Main.btnSquare21.setText(num9);}
        if(number_Choose == 12){Form_Main.btnSquare12.setText(num9);}
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     * 
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
