/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;
import static Form.Form_Main.number_Choose;
/**
 *
 * @author Ruster
 */
public class Form_Choice extends javax.swing.JDialog {
    /**
     * Creates new form Form_Choice
     */
    public Form_Choice(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnSo1 = new javax.swing.JButton();
        btnSo2 = new javax.swing.JButton();
        btnSo3 = new javax.swing.JButton();
        btnSo4 = new javax.swing.JButton();
        btnSo5 = new javax.swing.JButton();
        btnSo6 = new javax.swing.JButton();
        btnSo7 = new javax.swing.JButton();
        btnSo8 = new javax.swing.JButton();
        btnSo9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new java.awt.BorderLayout(0, 10));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        btnSo1.setBackground(new java.awt.Color(255, 255, 255));
        btnSo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSo1.setText("1");
        btnSo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo1ActionPerformed(evt);
            }
        });

        btnSo2.setBackground(new java.awt.Color(255, 255, 255));
        btnSo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSo2.setText("2");
        btnSo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo2ActionPerformed(evt);
            }
        });

        btnSo3.setBackground(new java.awt.Color(255, 255, 255));
        btnSo3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSo3.setText("3");
        btnSo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo3ActionPerformed(evt);
            }
        });

        btnSo4.setBackground(new java.awt.Color(255, 255, 255));
        btnSo4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSo4.setText("4");
        btnSo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo4ActionPerformed(evt);
            }
        });

        btnSo5.setBackground(new java.awt.Color(255, 255, 255));
        btnSo5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSo5.setText("5");
        btnSo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo5ActionPerformed(evt);
            }
        });

        btnSo6.setBackground(new java.awt.Color(255, 255, 255));
        btnSo6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSo6.setText("6");
        btnSo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo6ActionPerformed(evt);
            }
        });

        btnSo7.setBackground(new java.awt.Color(255, 255, 255));
        btnSo7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSo7.setText("7");
        btnSo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo7ActionPerformed(evt);
            }
        });

        btnSo8.setBackground(new java.awt.Color(255, 255, 255));
        btnSo8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSo8.setText("8");
        btnSo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo8ActionPerformed(evt);
            }
        });

        btnSo9.setBackground(new java.awt.Color(255, 255, 255));
        btnSo9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSo9.setText("9");
        btnSo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSo1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnSo2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnSo3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSo4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnSo5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnSo6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSo7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnSo8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnSo9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSo1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSo2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSo3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSo4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSo5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSo6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSo7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSo8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSo9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please make your decision:");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void setChoice(String number)
    {
        if(number_Choose == 1){Form_Main.btnSquare1.setText(number);}   if(number_Choose == 2){Form_Main.btnSquare2.setText(number);}
        if(number_Choose == 3){Form_Main.btnSquare3.setText(number);}   if(number_Choose == 4){Form_Main.btnSquare4.setText(number);}
        if(number_Choose == 5){Form_Main.btnSquare5.setText(number);}   if(number_Choose == 6){Form_Main.btnSquare6.setText(number);}
        if(number_Choose == 7){Form_Main.btnSquare7.setText(number);}   if(number_Choose == 8){Form_Main.btnSquare8.setText(number);}
        if(number_Choose == 9){Form_Main.btnSquare9.setText(number);}   if(number_Choose == 10){Form_Main.btnSquare10.setText(number);}
        if(number_Choose == 11){Form_Main.btnSquare11.setText(number);} if(number_Choose == 12){Form_Main.btnSquare12.setText(number);}
        if(number_Choose == 13){Form_Main.btnSquare13.setText(number);} if(number_Choose == 14){Form_Main.btnSquare14.setText(number);}
        if(number_Choose == 15){Form_Main.btnSquare15.setText(number);} if(number_Choose == 16){Form_Main.btnSquare16.setText(number);}
        if(number_Choose == 17){Form_Main.btnSquare17.setText(number);} if(number_Choose == 18){Form_Main.btnSquare18.setText(number);}
        if(number_Choose == 19){Form_Main.btnSquare19.setText(number);} if(number_Choose == 20){Form_Main.btnSquare20.setText(number);}
        if(number_Choose == 21){Form_Main.btnSquare21.setText(number);} if(number_Choose == 22){Form_Main.btnSquare22.setText(number);}
        if(number_Choose == 23){Form_Main.btnSquare23.setText(number);} if(number_Choose == 24){Form_Main.btnSquare24.setText(number);}
        if(number_Choose == 25){Form_Main.btnSquare25.setText(number);} if(number_Choose == 26){Form_Main.btnSquare26.setText(number);}
        if(number_Choose == 27){Form_Main.btnSquare27.setText(number);} if(number_Choose == 28){Form_Main.btnSquare28.setText(number);}
        if(number_Choose == 29){Form_Main.btnSquare29.setText(number);} if(number_Choose == 30){Form_Main.btnSquare30.setText(number);}
        if(number_Choose == 31){Form_Main.btnSquare31.setText(number);} if(number_Choose == 32){Form_Main.btnSquare32.setText(number);}
        if(number_Choose == 33){Form_Main.btnSquare33.setText(number);} if(number_Choose == 34){Form_Main.btnSquare34.setText(number);}
        if(number_Choose == 35){Form_Main.btnSquare35.setText(number);} if(number_Choose == 36){Form_Main.btnSquare36.setText(number);}
        if(number_Choose == 37){Form_Main.btnSquare37.setText(number);} if(number_Choose == 38){Form_Main.btnSquare38.setText(number);}
        if(number_Choose == 39){Form_Main.btnSquare39.setText(number);} if(number_Choose == 40){Form_Main.btnSquare40.setText(number);}
        if(number_Choose == 41){Form_Main.btnSquare41.setText(number);} if(number_Choose == 42){Form_Main.btnSquare42.setText(number);}
        if(number_Choose == 43){Form_Main.btnSquare43.setText(number);} if(number_Choose == 44){Form_Main.btnSquare44.setText(number);}
        if(number_Choose == 45){Form_Main.btnSquare45.setText(number);} if(number_Choose == 46){Form_Main.btnSquare46.setText(number);}
        if(number_Choose == 47){Form_Main.btnSquare47.setText(number);} if(number_Choose == 48){Form_Main.btnSquare48.setText(number);}
        if(number_Choose == 49){Form_Main.btnSquare49.setText(number);} if(number_Choose == 50){Form_Main.btnSquare50.setText(number);}
        if(number_Choose == 51){Form_Main.btnSquare51.setText(number);} if(number_Choose == 52){Form_Main.btnSquare52.setText(number);}
        if(number_Choose == 53){Form_Main.btnSquare53.setText(number);} if(number_Choose == 54){Form_Main.btnSquare54.setText(number);}
        if(number_Choose == 55){Form_Main.btnSquare55.setText(number);} if(number_Choose == 56){Form_Main.btnSquare56.setText(number);}
        if(number_Choose == 57){Form_Main.btnSquare57.setText(number);} if(number_Choose == 58){Form_Main.btnSquare58.setText(number);}
        if(number_Choose == 59){Form_Main.btnSquare59.setText(number);} if(number_Choose == 60){Form_Main.btnSquare60.setText(number);}
        if(number_Choose == 61){Form_Main.btnSquare61.setText(number);} if(number_Choose == 62){Form_Main.btnSquare62.setText(number);}
        if(number_Choose == 63){Form_Main.btnSquare63.setText(number);} if(number_Choose == 64){Form_Main.btnSquare64.setText(number);}
        if(number_Choose == 65){Form_Main.btnSquare65.setText(number);} if(number_Choose == 66){Form_Main.btnSquare66.setText(number);}
        if(number_Choose == 67){Form_Main.btnSquare67.setText(number);} if(number_Choose == 68){Form_Main.btnSquare68.setText(number);}
        if(number_Choose == 69){Form_Main.btnSquare69.setText(number);} if(number_Choose == 70){Form_Main.btnSquare70.setText(number);}
        if(number_Choose == 71){Form_Main.btnSquare71.setText(number);} if(number_Choose == 72){Form_Main.btnSquare72.setText(number);}
        if(number_Choose == 73){Form_Main.btnSquare73.setText(number);} if(number_Choose == 74){Form_Main.btnSquare74.setText(number);}
        if(number_Choose == 75){Form_Main.btnSquare75.setText(number);} if(number_Choose == 76){Form_Main.btnSquare76.setText(number);}
        if(number_Choose == 77){Form_Main.btnSquare77.setText(number);} if(number_Choose == 78){Form_Main.btnSquare78.setText(number);}
        if(number_Choose == 79){Form_Main.btnSquare79.setText(number);} if(number_Choose == 80){Form_Main.btnSquare80.setText(number);}
        if(number_Choose == 81){Form_Main.btnSquare81.setText(number);}
    }
    private void btnSo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo1ActionPerformed
        String number = "1";
        setChoice(number);
        dispose();
    }//GEN-LAST:event_btnSo1ActionPerformed

    private void btnSo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo2ActionPerformed
        String number = "2";
        setChoice(number);
        dispose();
    }//GEN-LAST:event_btnSo2ActionPerformed

    private void btnSo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo3ActionPerformed
        String number = "3";
        setChoice(number);
        dispose();
    }//GEN-LAST:event_btnSo3ActionPerformed

    private void btnSo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo4ActionPerformed
        String number = "4";
        setChoice(number);
        dispose();
    }//GEN-LAST:event_btnSo4ActionPerformed

    private void btnSo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo5ActionPerformed
        String number = "5";
        setChoice(number);
        dispose();
    }//GEN-LAST:event_btnSo5ActionPerformed

    private void btnSo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo6ActionPerformed
        String number = "6";
        setChoice(number);
        dispose();
    }//GEN-LAST:event_btnSo6ActionPerformed

    private void btnSo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo7ActionPerformed
        String number = "7";
        setChoice(number);
        dispose();
    }//GEN-LAST:event_btnSo7ActionPerformed

    private void btnSo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo8ActionPerformed
        String number = "8";
        setChoice(number);
        dispose();
    }//GEN-LAST:event_btnSo8ActionPerformed

    private void btnSo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo9ActionPerformed
        String number = "9";
        setChoice(number);
        dispose();
    }//GEN-LAST:event_btnSo9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Choice dialog = new Form_Choice(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnSo1;
    public static javax.swing.JButton btnSo2;
    private javax.swing.JButton btnSo3;
    private javax.swing.JButton btnSo4;
    private javax.swing.JButton btnSo5;
    private javax.swing.JButton btnSo6;
    private javax.swing.JButton btnSo7;
    private javax.swing.JButton btnSo8;
    private javax.swing.JButton btnSo9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
